/* global React */
// Historial consolidado de reuniones Credicorp × +Partners (dic-2025 → jul-2026).
// Fuente: Historial Consolidado Reuniones Credicorp 2025-2026 (Sheet) + continuación may-jun + match de transcripts.
// Resúmenes livianos: tema en 1 línea, sin detalle interno.
// p: hub-brasil | alicia | romy | desempeno | partners

const MEETINGS_HISTORY = [
  { f: "2025-12-02", t: "Proyecto +Partners / Credicorp — kickoff", p: "partners", who: ["Mara","Jorge","Sasan","Juan","Lucía","Pablo Silva"], r: "Arranque del programa: alcance, frentes y forma de trabajo." },
  { f: "2025-12-11", t: "Wellhub / Credicorp", p: "hub-brasil", who: ["Mara","Jorge","Sasan","Pablo Silva"], ext: "Wellhub", link: "https://fathom.video/calls/503107422", r: "Intercambio con Wellhub sobre beneficios de bienestar en Brasil." },
  { f: "2025-12-12", t: "HUB BR — Proyecto +Partners / Credicorp", p: "hub-brasil", who: ["Jorge","Sasan","Mara","Pablo Silva","Lucila Guelfo"], r: "Sesión de trabajo del frente Hub Brasil." },
  { f: "2025-12-12", t: "Gestión del desempeño", p: "desempeno", who: ["Jorge","Sasan","Mara","Gisselle"], r: "Apertura del frente de performance con Gisselle." },
  { f: "2025-12-12", t: "Edenred / Credicorp", p: "hub-brasil", who: ["Mara","Jorge","Pablo Silva","Lucila Guelfo"], ext: "Edenred", r: "Intercambio con Edenred sobre beneficios (VR/VA) en Brasil." },
  { f: "2025-12-15", t: "Seteo de tareas automatizables", p: "desempeno", who: ["Mara","Lucía","Gisselle"], r: "Identificación de tareas automatizables del área." },
  { f: "2025-12-16", t: "HUB BR — Proyecto +Partners / Credicorp", p: "hub-brasil", who: ["Mara","Jorge","Sasan","Pablo Silva","Lucila Guelfo"], r: "Sesión de trabajo del frente Hub Brasil." },
  { f: "2025-12-22", t: "Demo Humand + Grupo Credicorp", p: "desempeno", who: ["Jorge","Sasan","Mara","Lucía"], ext: "Humand", r: "Demo de plataforma Humand." },
  { f: "2025-12-29", t: "Mandú by Visma — intro", p: "desempeno", who: ["Jorge","Sasan","Mara"], ext: "Visma", link: "https://fathom.video/calls/518374348", r: "Presentación de Mandú (Visma) como herramienta de gestión." },
  { f: "2026-01-02", t: "Sync interno previo a Credicorp", p: "partners", who: ["Equipo +Partners"], link: "https://fathom.video/share/8a1MMbg754aLfv9EaZFabRz_saxr-eVS", r: "Alineación interna de arranque de año." },
  { f: "2026-01-08", t: "Reunión de seguimiento HUB BR", p: "hub-brasil", who: ["Equipo +Partners","Credicorp"], link: "https://fathom.video/share/JqxA1RJFSNy3CzstCboz71sSMvr_xh4Z", r: "Seguimiento del frente Hub Brasil." },
  { f: "2026-01-09", t: "Call GC + Partners", p: "hub-brasil", who: ["Mara","Lucía","Lucila Guelfo","Juan"], r: "Coordinación con Grupo Crédito." },
  { f: "2026-01-09", t: "Mercer Brasil / Credicorp", p: "hub-brasil", who: ["Jorge","Sasan","Mara"], ext: "Mercer", r: "Intercambio con Mercer Brasil sobre mercado y compensaciones." },
  { f: "2026-01-12", t: "Alex Saia", p: "partners", who: ["Equipo +Partners"], r: "Contacto del ecosistema Brasil." },
  { f: "2026-01-13", t: "Demo Sólides Tecnologia", p: "hub-brasil", who: ["Jorge","Sasan","Mara"], ext: "Sólides", r: "Demo de HR tech brasileña Sólides." },
  { f: "2026-01-13", t: "Cámara Software Brasil", p: "partners", who: ["Equipo +Partners"], ext: "Cámara Software BR", link: "https://fathom.video/share/kvDjxwAEqS-FDgx_xXcmzeMTAaExsZ6o", r: "Contacto institucional con la cámara de software de Brasil." },
  { f: "2026-01-14", t: "Boas práticas — C6 Bank", p: "hub-brasil", who: ["Jorge","Mara","Lucila Guelfo"], ext: "C6 Bank", r: "Benchmark de prácticas de talento con C6 Bank." },
  { f: "2026-01-15", t: "Caju <> Credicorp", p: "hub-brasil", who: ["Jorge","Lucila Guelfo"], ext: "Caju", r: "Intercambio con Caju sobre beneficios flexibles." },
  { f: "2026-01-19", t: "Amazon BR / Credicorp", p: "hub-brasil", who: ["Lucía","Sasan","Lucila Guelfo","Jorge","Pablo Silva"], ext: "Amazon", r: "Intercambio regional con Amazon Brasil." },
  { f: "2026-01-21", t: "Clara BR / Credicorp", p: "hub-brasil", who: ["Jorge","Pablo Silva","Lucila Guelfo"], ext: "Clara", r: "Intercambio con Clara sobre operación en Brasil." },
  { f: "2026-01-23", t: "Reunião online — SulAmérica", p: "hub-brasil", who: ["Sasan"], ext: "SulAmérica", r: "Contacto con SulAmérica (seguros/salud)." },
  { f: "2026-01-29", t: "Intercambio regional: Adidas", p: "hub-brasil", who: ["Sasan","Mara","Lucila Guelfo"], ext: "Adidas", r: "Benchmark regional de talento con Adidas." },
  { f: "2026-01-29", t: "Acrisure greets Credicorp", p: "hub-brasil", who: ["Jorge","Sasan","Lucila Guelfo"], ext: "Acrisure", r: "Presentación de Acrisure." },
  { f: "2026-02-03", t: "Globus Seguros / Credicorp", p: "hub-brasil", who: ["Mara","Jorge","Lucila Guelfo"], ext: "Globus Seguros", r: "Intercambio sobre seguros para el Hub." },
  { f: "2026-02-06", t: "Intercambio regional: Koin (BR)", p: "hub-brasil", who: ["Jorge","Pablo Silva","Lucila Guelfo"], ext: "Koin", r: "Benchmark con Koin sobre operación tech en Brasil." },
  { f: "2026-02-09", t: "Stone <> Credicorp Perú", p: "hub-brasil", who: ["Jorge","Pablo Silva"], ext: "Stone", r: "Benchmark con Stone sobre talento tech en Brasil." },
  { f: "2026-02-11", t: "Apresentação Apdata", p: "hub-brasil", who: ["Equipo +Partners"], ext: "Apdata", r: "Demo de Apdata (HR tech BR)." },
  { f: "2026-02-23", t: "Revisión Bot Objetivos", p: "desempeno", who: ["Mara","Sasan","Gisselle"], r: "Revisión del bot de establecimiento de objetivos (GiseGPT)." },
  { f: "2026-02-27", t: "Intercambio: Banco Galicia (ARG)", p: "desempeno", who: ["Jorge","Pablo Silva"], ext: "Banco Galicia", r: "Benchmark de performance con Banco Galicia." },
  { f: "2026-03-03", t: "Philips — Movilidad HR", p: "romy", who: ["Mara","Pablo Silva","Romina"], ext: "Philips", r: "Benchmark de movilidad internacional con Philips LATAM." },
  { f: "2026-03-06", t: "Benchmarking Nubank — Mobility", p: "romy", who: ["Mara","Jorge","Romina"], ext: "Nubank", r: "Benchmark de movilidad con Nubank." },
  { f: "2026-03-09", t: "HR Innovation Sprints", p: "alicia", who: ["Equipo +Partners","Credicorp"], link: "https://fathom.video/calls/591842606", r: "Sesión de sprints de innovación HR." },
  { f: "2026-03-10", t: "Seguimiento HR proyecto Mobility", p: "partners", who: ["Equipo +Partners"], link: "https://fathom.video/calls/594667326", r: "Seguimiento interno del frente Mobility." },
  { f: "2026-03-13", t: "Credicorp — Mobility", p: "romy", who: ["Jorge","Romina","Mara","Lucía"], link: "https://fathom.video/share/z7hya-sLFn3cPfa1f2fi8sThkTBUiA7o", r: "Sesión de trabajo del programa Mobility 360." },
  { f: "2026-03-16", t: "Playbook Mobility", p: "romy", who: ["Mara","Lucía","Romina"], r: "Armado del playbook de movilidad." },
  { f: "2026-03-16", t: "Seguimiento proyecto Credicorp", p: "partners", who: ["Jorge","Sasan","Mara","Juan"], link: "https://fathom.video/share/ULFiTUFJvXxvcwqXxQsXxwGoAPn4s-c_", r: "Seguimiento interno de los frentes." },
  { f: "2026-03-17", t: "MeLi <> Credicorp — Mobility bench", p: "romy", who: ["Mara","Jorge","Romina"], ext: "Mercado Libre", r: "Benchmark de movilidad con Mercado Libre." },
  { f: "2026-03-19", t: "HR Innovation Sprint (Alicia)", p: "alicia", who: ["Equipo +Partners","Credicorp"], r: "Primera sesión del sprint con el equipo de Alicia." },
  { f: "2026-03-20", t: "5ta sesión Mobility 360 / Hub Brasil", p: "hub-brasil", who: ["Jorge","Sasan","Mara","Romina"], link: "https://fathom.video/share/BQ32CAsWPdyG8mweCpwR7Bhsh5MHTiW_", r: "Status del Hub: dependencias, ruta crítica y plan de destrabe." },
  { f: "2026-03-25", t: "Accenture — Credicorp", p: "romy", who: ["Mara","Romina"], ext: "Accenture", link: "https://fathom.video/share/s72jE_zfC2bVjnzLvmdrmnSGV1e7snqY", r: "Benchmark de movilidad y EVP con Accenture." },
  { f: "2026-03-30", t: "Seguimiento proyecto Credicorp", p: "partners", who: ["Jorge","Sasan","Mara","Juan"], r: "Seguimiento interno de los frentes." },
  { f: "2026-03-30", t: "HR Innovation Sprint (Alicia) — sesión 2", p: "alicia", who: ["Pablo Silva","Alicia Rivera","Lucía","Mara"], r: "Análisis de procesos de incentivos y onboarding." },
  { f: "2026-03-30", t: "Credicorp / Boehringer", p: "romy", who: ["Jorge","Pablo Silva","Romina"], ext: "Boehringer", r: "Benchmark de movilidad con Boehringer Ingelheim." },
  { f: "2026-03-31", t: "Hub Brasil — Change Management", p: "hub-brasil", who: ["Jorge","Lucía","Juan","Lucila Guelfo"], r: "Arranque del plan de change para el Hub." },
  { f: "2026-04-06", t: "Seguimiento proyecto Credicorp", p: "partners", who: ["Jorge","Sasan","Mara","Lucía","Juan"], r: "Seguimiento interno de los frentes." },
  { f: "2026-04-08", t: "Preparar reunión con Pablo", p: "partners", who: ["Jorge","Sasan","Lucía","Mara"], r: "Preparación interna de la reunión de status." },
  { f: "2026-04-09", t: "HR Innovation Sprints — abril (con Pablo)", p: "partners", who: ["Jorge","Juan","Mara","Sasan","Pablo Silva","Lucía"], link: "https://fathom.video/calls/631646507", r: "Status con Pablo: activación de Onboarding TOPS y escalado del bloqueo IT." },
  { f: "2026-04-10", t: "Sesión Mobility 360", p: "romy", who: ["Mara","Jorge","Lucía","Juan","Romina"], r: "Sesión de trabajo del programa Mobility 360." },
  { f: "2026-04-10", t: "HUB Brasil — proveedores de nómina", p: "hub-brasil", who: ["Mara","Sasan","Lucía","Juan","Lucila Guelfo"], r: "Mapa de proveedores de nómina para el Hub." },
  { f: "2026-04-13", t: "LG lugar de gente — levantamiento", p: "hub-brasil", who: ["Mara","Lucía","Lucila Guelfo"], ext: "LG lugar de gente", link: "https://fathom.video/share/tbAMHW1TtKqa4y834tjnUiAiw5phu6DG", r: "Levantamiento con LG: alcance del software vs BPO de nómina." },
  { f: "2026-04-13", t: "Seguimiento proyecto Credicorp", p: "partners", who: ["Sasan","Mara","Lucía"], r: "Seguimiento interno de los frentes." },
  { f: "2026-04-14", t: "Auxadi — contacto por Grupo Credicorp en Brasil", p: "hub-brasil", who: ["Mara","Jorge","Sasan"], ext: "Auxadi", r: "Presentación de Auxadi como candidato a BPO de nómina." },
  { f: "2026-04-14", t: "HUB Brasil — Plan de Change Management", p: "hub-brasil", who: ["Jorge","Sasan","Mara","Lucila Guelfo","Pablo Silva"], r: "Plan de change del Hub con el sponsor." },
  { f: "2026-04-14", t: "ADP — reunión proveedores", p: "hub-brasil", who: ["Jorge","Sasan","Mara"], ext: "ADP", r: "Presentación de ADP como candidato a BPO de nómina." },
  { f: "2026-04-15", t: "Proyecto HUB BR — Change Management", p: "hub-brasil", who: ["Jorge","Juan","Lucía","Mara","Sasan","Lucila Guelfo"], link: "https://fathom.video/share/7EJbxjmFY2YcXnK6QT8JypPjq8uCzpEr", r: "Diseño del plan de comunicación del lanzamiento del Hub." },
  { f: "2026-04-16", t: "Reu Lu + Mara", p: "hub-brasil", who: ["Mara","Lucila Guelfo","Lucía"], link: "https://fathom.video/share/X1hwa6HyM86e-6yz4u2eG7F1JL8KxddW", r: "Coordinación semanal con Lu." },
  { f: "2026-04-20", t: "Seguimiento proyecto Credicorp", p: "partners", who: ["Jorge","Juan","Lucía","Sasan","Mara"], link: "https://fathom.video/calls/641242179", r: "Seguimiento interno de los frentes." },
  { f: "2026-04-21", t: "Sesión Mobility 360", p: "romy", who: ["Mara","Lucía","Jorge","Romina"], r: "Sesión de trabajo del programa Mobility 360." },
  { f: "2026-04-24", t: "Reunión con Alicia — seteo de objetivos", p: "alicia", who: ["Lucía","Mara","Pablo Silva","Alicia Rivera"], r: "Seteo de objetivos del frente Onboarding TOPS." },
  { f: "2026-04-27", t: "Seguimiento proyecto Credicorp", p: "partners", who: ["Sasan","Mara","Lucía"], link: "https://fathom.video/share/UrapLfjGwHwxU9A8rxN6mHfQj_s3FCCF", r: "Seguimiento interno de los frentes." },
  { f: "2026-04-27", t: "Seguimiento — parte 2", p: "partners", who: ["Sasan","Mara","Lucía"], link: "https://fathom.video/calls/652626993", r: "Continuación del seguimiento interno." },
  { f: "2026-04-29", t: "Mobility — reunión con Romy", p: "romy", who: ["Mara","Lucía","Jorge","Romina"], r: "Sesión de trabajo con Romina." },
  { f: "2026-05-04", t: "Seguimiento", p: "partners", who: ["Lucía","Juan","Mara"], r: "Seguimiento interno de los frentes." },
  { f: "2026-05-11", t: "Seguimiento proyecto Credicorp", p: "partners", who: ["Jorge","Juan","Lucía","Mara","Sasan"], link: "https://fathom.video/share/jyHYtpnYmsy13fpznTQkrbstyPJ2yUCS", r: "Repaso de los 4 frentes y preparación del status con Pablo." },
  { f: "2026-05-14", t: "Mobility — Onboarding Blueprint", p: "alicia", who: ["Lucía","Juan","Mara","Alicia Rivera"], r: "Blueprint de onboarding: Pacífico Seguros y Prima AFP." },
  { f: "2026-05-15", t: "Seguimiento", p: "partners", who: ["Jorge","Juan","Lucía","Mara","Sasan"], r: "Seguimiento interno de los frentes." },
  { f: "2026-05-18", t: "Seguimiento proyectos HR Sprints (con Pablo)", p: "partners", who: ["Jorge","Juan","Lucía","Mara","Sasan","Pablo Silva"], r: "Status de proyectos con Pablo." },
  { f: "2026-05-18", t: "Revisión Blueprint — Hub Brasil", p: "hub-brasil", who: ["Lucía","Juan","Lucila Guelfo"], r: "Revisión del blueprint operativo del Hub." },
  { f: "2026-05-20", t: "Sesión Mobility 360", p: "romy", who: ["Mara","Jorge","Lucía","Romina"], r: "Sesión de cierre de entregables Mobility." },
  { f: "2026-05-21", t: "Coordinaciones — benchmark de movilidad", p: "romy", who: ["Mara","Romina","Lucía"], r: "Coordinación del benchmark de movilidad internacional." },
  { f: "2026-05-22", t: "Preparación sesión HR", p: "alicia", who: ["Mara","Lucía","Juan"], r: "Preparación interna de la sesión con el equipo de Alicia." },
  { f: "2026-05-22", t: "Debrief Onboarding Credicorp", p: "alicia", who: ["Mara","Jorge","Juan","Lucía","Sasan"], r: "Debrief interno del relevamiento de onboarding." },
  { f: "2026-05-26", t: "Seguimiento proyecto Credicorp", p: "partners", who: ["Mara","Jorge","Sasan","Juan","Lucía"], r: "Seguimiento interno de los frentes." },
  { f: "2026-05-27", t: "Onboarding Pacífico Salud", p: "alicia", who: ["Mara","Equipo +Partners","Alicia Rivera"], r: "Relevamiento de onboarding en Pacífico Salud." },
  { f: "2026-05-28", t: "Preparar presentación a Alicia", p: "alicia", who: ["Mara","Jorge","Sasan","Juan","Lucía"], r: "Preparación interna de la presentación." },
  { f: "2026-05-28", t: "Hub Brasil — seguimiento", p: "hub-brasil", who: ["Lucila Guelfo","Mara","Lucía","Juan","Jorge","Sasan"], r: "Seguimiento del frente Hub Brasil." },
  { f: "2026-05-29", t: "Onboarding TOPS — sesión de trabajo", p: "alicia", who: ["Mara","Pablo Silva","Alicia Rivera"], r: "Sesión de trabajo del frente Onboarding TOPS." },
  { f: "2026-06-01", t: "Catchup Credicorp", p: "partners", who: ["Jorge","Sasan","Mara","Lucía"], r: "Catchup interno de los frentes." },
  { f: "2026-06-03", t: "Onboarding Nubank", p: "alicia", who: ["Mara","Equipo +Partners","Credicorp"], ext: "Nubank", r: "Benchmark de onboarding ejecutivo con Nubank." },
  { f: "2026-06-04", t: "Onboarding Credicorp", p: "alicia", who: ["Alicia Rivera","Mara","Equipo +Partners","BCP"], r: "Sesión de trabajo de onboarding con Alicia." },
  { f: "2026-06-05", t: "Hub Brasil — revisión y avances", p: "hub-brasil", who: ["Lucila Guelfo","Mara","Lucía","Juan"], r: "Revisión de avances del Hub." },
  { f: "2026-06-08", t: "Hub Brasil — estructura de reuniones", p: "hub-brasil", who: ["Lucila Guelfo","Mara","Lucía","Juan"], r: "Definición de la estructura de seguimiento del Hub." },
  { f: "2026-06-08", t: "Onboarding Credicorp", p: "alicia", who: ["Alicia Rivera","Mara","Equipo +Partners","BCP"], r: "Sesión de trabajo de onboarding con Alicia." },
  { f: "2026-06-10", t: "Onboarding Credicorp", p: "alicia", who: ["Alicia Rivera","Mara","Equipo +Partners","BCP"], r: "Sesión de trabajo de onboarding con Alicia." },
  { f: "2026-06-16", t: "Catchup con Mara y Lu", p: "hub-brasil", who: ["Mara","Jorge","Sasan","Lucía","Juan"], r: "Catchup del frente Hub Brasil." },
  { f: "2026-06-16", t: "Onboarding Credicorp", p: "alicia", who: ["Alicia Rivera","Mara","Equipo +Partners","BCP"], r: "Sesión de trabajo de onboarding con Alicia." },
  { f: "2026-06-17", t: "Catchup Mara y Lu", p: "hub-brasil", who: ["Lucila Guelfo","Lucía","Mara"], r: "Coordinación semanal con Lu." },
  { f: "2026-06-18", t: "Onboarding Banco Galicia", p: "alicia", who: ["Mara","Credicorp","BCP"], ext: "Banco Galicia", r: "Benchmark de onboarding ejecutivo con Banco Galicia." },
  { f: "2026-06-19", t: "TMF Group — servicios de nómina", p: "hub-brasil", who: ["Lucila Guelfo","Mara","Lucía"], ext: "TMF", r: "Presentación de datos y condiciones de TMF para la nómina." },
  { f: "2026-06-22", t: "HUB BR — Change Management", p: "hub-brasil", who: ["Jorge","Sasan","Mara","Lucía","Lucila Guelfo"], r: "Sesión de trabajo del plan de change." },
  { f: "2026-06-22", t: "Hub Brasil — Plan de Change (con Pablo)", p: "hub-brasil", who: ["Lucila Guelfo","Mara","Sasan","Pablo Silva"], r: "Presentación del plan de change al sponsor." },
  { f: "2026-06-24", t: "Onboarding Banco Santander", p: "alicia", who: ["Mara","Credicorp","BCP"], ext: "Santander", r: "Benchmark de onboarding ejecutivo con Santander." },
  { f: "2026-06-29", t: "BCP y Mara — catchup", p: "partners", who: ["Sasan","Mara","Jorge","Juan"], r: "Catchup breve del equipo." },
  { f: "2026-07-02", t: "Preparación Pablo (interna)", p: "partners", who: ["Mara","Sasan","Jorge","Juan","Lucía"], link: "https://fathom.video/calls/731790008", r: "Preparación del status: narrativa por frente y próximos pasos." },
  { f: "2026-07-02", t: "Status de proyectos con Pablo Silva", p: "partners", who: ["Pablo Silva","Mara","Equipo +Partners"], r: "Repaso de los 4 frentes a 8 meses de programa; prioridad Hub Brasil." },
];

window.MEETINGS_HISTORY = MEETINGS_HISTORY;
